apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-app-deployment
  namespace: e-store
spec:
  selector:
    matchLabels:
      app: orders-app-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: orders-app-deployment
    spec:
      containers:
        - name: orders-app-container
          image: rso6315/orders-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: KUMULUZEE_DISCOVERY_CLUSTER
              value: third-cluster
            - name: KUMULUZEE_DISCOVERY_CONSUL_AGENT
              value: http://consul-service-consul-server.e-store:8500
            - name: KUMULUZEE_CONFIG_CONSUL_AGENT
              value: http://consul-service-consul-server.e-store:8500
            - name: KUMULUZEE_SERVER_BASEURL
              value: http://35.246.208.18/orders-service
            - name: KUMULUZEE_STREAMING_KAFKA_PRODUCER_BOOTSTRAP-SERVERS
              value: kafka-service.e-store:9092
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgresql://orders-db.e-store:5432/orders
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              value: postgres
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: orders-pass
                  key: POSTGRES_PASSWORD
            - name: KUMULUZEE_GRPC_CLIENTS0_ADDRESS
              value: customers-service.e-store
            - name: KUMULUZEE_GRPC_CLIENTS0_PORT
              value: "8443"
            - name: KUMULUZEE_GRPC_CLIENTS1_ADDRESS
              value: invoice-service.e-store
            - name: KUMULUZEE_GRPC_CLIENTS1_PORT
              value: "8443"
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 3
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: orders-service
  name: orders-service
  namespace: e-store
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 31017
      targetPort: 8080
      protocol: TCP
  selector:
    app: orders-app-deployment
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: orders-app-autoscaler
  namespace: e-store
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: orders-app-deployment
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 30
