apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-app-deployment
  namespace: e-store
spec:
  selector:
    matchLabels:
      app: orders-app-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: orders-app-deployment
    spec:
      containers:
        - name: orders-app-container
          image: rso6315/orders-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgresql://orders-db.e-store:5432/orders
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              value: postgres
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: orders-pass
                  key: POSTGRES_PASSWORD
      #          readinessProbe:
      #            httpGet:
      #              path: /health/live
      #              port: 8082
      #              httpHeaders:
      #                - name: Custom-Header
      #                  value: Awesome
      #            initialDelaySeconds: 3
      #            periodSeconds: 3
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: orders-service
  name: orders-service
  namespace: e-store
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 31017
      targetPort: 8080
      protocol: TCP
  selector:
    app: orders-app-deployment